### ISSUE TITLE
Cannot run project on jetty server

### ISSUE THREAD

**Issue by kimxuyenthien** [gnostix/freeswitch-monitoring#6]
i run on jetty and got error not found "user/login", please help me 

<img width="1437" alt="screen shot 2018-07-26 at 11 34 54 pm" src="https://user-images.githubusercontent.com/10683955/43275657-9a5bb14c-912c-11e8-9f21-5cce0601c0b2.png">

**Comment by gnostix** [comment]
The login should work if you followed the steps. Nevertheless, you can also move directly to the Dashboard page since the login page is more like a placeholder for now. The development is frozen due to no feedback from the community and that is why this feature is not activated.
http://localhost:8080/dashboard.html
